### ISSUE TITLE
nix flake check does not work

### ISSUE THREAD

**Issue by chrishrb** [BirdeeHub/nixCats-nvim#19]
I have the following error if I try to run the `nix flake check` command:

```
nix flake check .

warning: creating lock file '/Users/chrishrb/dev/home/bla/flake.lock'
warning: unknown flake output 'utils'
warning: unknown flake output 'dependencyOverlays'
warning: unknown flake output 'categoryDefinitions'
warning: unknown flake output 'packageDefinitions'
warning: unknown flake output 'baseBuilder'
warning: unknown flake output 'customPackager'
error:
       … while checking flake output 'overlays'

         at /nix/store/na7sykizsgkzh9i3wc8m8pz5xfqib2rv-source/lib.nix:39:17:

           38|               {
           39|                 ${key} = (attrs.${key} or { })
             |                 ^
           40|                   // { ${system} = ret.${key}; };

       … while checking the overlay 'overlays.x86_64-linux'

         at /nix/store/na7sykizsgkzh9i3wc8m8pz5xfqib2rv-source/lib.nix:40:24:

           39|                 ${key} = (attrs.${key} or { })
           40|                   // { ${system} = ret.${key}; };
             |                        ^
           41|               }

       error: overlay is not a function, but a set instead
```

To reproduce:

```bash
mkdir nix-cats && cd nix-cats
nix flake init -t github:BirdeeHub/nixCats-nvim
nix flake check .
```

**Comment by BirdeeHub** [comment]
Hmmmm....


So, it appears this is because the overlays from nixCats are at overlays.${system}.packageName

I will need to look into this, but it's possible that this is simply due to the need to use flake-utils.eachSystem?

I actually did not know about this command

**Comment by BirdeeHub** [comment]
hmmmm Yep its because the overlays are output from within flake-utils.

The overlays just contain the final package. they are at overlays.${system}.packagename instead of at overlays.packagename

I can rework that output. I am not sure many people are using it, as its usually easier to just pass the package where you want yourself. Seems worthwile, hopefully I can do it in a way that isnt messy.

**Comment by BirdeeHub** [comment]
[this is currently how the overlays output works. Very simple.](https://github.com/BirdeeHub/nixCats-nvim/blob/60b70f861f253419fced2293de27c031d052b1a0/nix/utils/default.nix#L24C1-L35C93)

[and where it gets exported](https://github.com/BirdeeHub/nixCats-nvim/blob/60b70f861f253419fced2293de27c031d052b1a0/flake.nix#L385)

the issue is, these functions assume you already told the builder what system it was building for....

So it gets output behind flake-utils so that its outputs.overlays.${pkgs.system}.packagename

So to change it, I would need to do a little bit of messing around.

I dont want to break anything other than the overlays output when I do so, so that people can just put the 1 new line into their flake.nix for the overlays output and be done with it when i make the change

**Comment by BirdeeHub** [comment]
``nix
    # choose your package for devShell
    # and add whatever else you want in it.
    devShells = {
      default = pkgs.mkShell {
        name = defaultPackageName;
        packages = [ (nixCatsBuilder defaultPackageName) ];
        inputsFrom = [ ];
        shellHook = ''
        '';
      };
    };
```

I also need to change the devShells output to the above. because the current one is deprecated, fyi

**Comment by BirdeeHub** [comment]
https://github.com/BirdeeHub/nixCats-nvim/tree/overlaysCheckFix

I have a working makeOverlays function and a (maybe working?) depreciation warning for the old one in this branch.

Still need to update the help and stuff, and test that I actually did the depreciation warning correctly before I merge it, but the main flake and the templates are all updated and work with nix flake check . in that branch.

**Comment by BirdeeHub** [comment]
Lmao I think I made someone mad cause someone unstarred. That's ok. It's a better project now that that issue is fixed.
