### ISSUE TITLE
Queries installed using `installQueries = true` are not included

### ISSUE THREAD

**Issue by PerchunPak** [BirdeeHub/nixCats-nvim#70]
Consider this overlay:

```nix
final: prev: {
  vimPlugins = prev.vimPlugins // {
    nvim-treesitter-parsers = prev.vimPlugins.nvim-treesitter-parsers // {
      nu = prev.vimPlugins.nvim-treesitter-parsers.nu.overrideAttrs {
        installQueries = true;
      };
    };
  };
}
```

Results into

```sh
$ ls /nix/store/n94w0bbsb1qpkjipqc726qkh4670l26g-vimplugin-treesitter-grammar-ALL-INCLUDED
/nix/store/n94w0bbsb1qpkjipqc726qkh4670l26g-vimplugin-treesitter-grammar-ALL-INCLUDED/parser
```

**Comment by PerchunPak** [comment]
Looks like overlays for nvim-treesitter-parsers generally don't work, setting src to something illegal (e.g. `hash = ""`) didn't produce an error

**Comment by BirdeeHub** [comment]
https://github.com/BirdeeHub/nixCats-nvim/blob/c1507cc417534ea657b03fcdb6859abe6a00c8d5/builder/vim-pack-dir.nix#L97-L110

^ What happens if you set the setting `collate_grammars = false;`

There are 2 ways grammars are processed by nixCats.

1. if collate_grammars is true, all grammars with a name matching `(builtins.match "^vimplugin-treesitter-grammar-.*" "${lib.getName drv}") != null;` will be combined via symlinkJoin like so

```nix
    ts_grammar_plugin_combined = symlinkJoin {
      name = "vimplugin-treesitter-grammar-ALL-INCLUDED";
      paths = map (e: e.outPath) collected_grammars;
    };
```

2. if collate_grammars is false, all grammars with a name matching `(builtins.match "^vimplugin-treesitter-grammar-.*" "${lib.getName drv}") != null;` will be simply added to `pack/myNeovimGrammars/start` with no modifications.

---

nu seems to not be throwing errors for me but it doesnt include queries either? I will do more testing myself but I would be interested to know what you see if you set `collate_grammars = false` for your package

**Comment by PerchunPak** [comment]
This was a bug in nixpkgs, `nvim-treesitter.withAllGrammars` doesn't support overrides. Filing a PR rn
